GET http://localhost:3001/api/people

### broken get

GET http://localhost:3001/persons/4

###

GET http://localhost:3001/api/people/d69987f8-d896-4773-8981-ed20523501f6

###

POST http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Ro",
    "number": "06-24242424"

}

### No content

POST http://localhost:3001/api/people/
Content-Type: application/json

### wrong ID

DELETE http://localhost:3001/api/people/b0454504b305a14369f20566


### malformatted ID

DELETE http://localhost:3001/api/people/66

###
GET http://localhost:3001/api/people/679ce928193e25a16aa80a6f